export interface DemoStud {
  id: string
  name: string
  breed: string
  color: string
  genetics: string
  weight_lbs: number
  age_years: number
  stud_fee: number
  contact_for_price: boolean
  city: string
  state: string
  country: string
  is_proven: boolean
  health_tested: boolean
  akc_registered: boolean
  description: string
  photos: string[]
  availability: string
  status: string
  is_featured: boolean
  owner_name: string
  owner_since: string
}

export const DEMO_STUDS: DemoStud[] = [
  {
    id: 'demo-1',
    name: 'Zeus',
    breed: 'French Bulldog',
    color: 'Blue Merle',
    genetics: 'Carries chocolate, tan',
    weight_lbs: 28,
    age_years: 3,
    stud_fee: 2500,
    contact_for_price: false,
    city: 'Los Angeles',
    state: 'CA',
    country: 'US',
    is_proven: true,
    health_tested: true,
    akc_registered: true,
    description: 'Zeus is a structurally sound Blue Merle French Bulldog with a wide chest, correct bite, and compact build. He has produced multiple litters with excellent confirmation and color. Health panel completed with clear results across all major genetic markers. Available for approved females with health testing on file.',
    photos: ['https://images.dog.ceo/breeds/bulldog-french/n02108915_12460.jpg', 'https://images.dog.ceo/breeds/bulldog-french/n02108915_2545.jpg', 'https://images.dog.ceo/breeds/bulldog-french/n02108915_5319.jpg'],
    availability: 'available',
    status: 'active',
    is_featured: true,
    owner_name: 'Mike R.',
    owner_since: '2022',
  },
  {
    id: 'demo-2',
    name: 'Apollo',
    breed: 'English Bulldog',
    color: 'Brindle & White',
    genetics: '',
    weight_lbs: 55,
    age_years: 4,
    stud_fee: 2000,
    contact_for_price: false,
    city: 'San Diego',
    state: 'CA',
    country: 'US',
    is_proven: true,
    health_tested: true,
    akc_registered: true,
    description: 'Apollo is an English Bulldog with heavy wrinkle, a wide, blocky head, and short, compact body. He has three proven litters producing consistent type. All health testing current. Excellent producer for structure and head type.',
    photos: ['https://images.dog.ceo/breeds/bulldog-english/bunz.jpg', 'https://images.dog.ceo/breeds/bulldog-english/bunz.jpg'],
    availability: 'available',
    status: 'active',
    is_featured: true,
    owner_name: 'Sarah K.',
    owner_since: '2021',
  },
  {
    id: 'demo-3',
    name: 'Titan',
    breed: 'French Bulldog',
    color: 'Lilac Tan',
    genetics: 'Fluffy carrier, chocolate, tan',
    weight_lbs: 26,
    age_years: 2.5,
    stud_fee: 4000,
    contact_for_price: false,
    city: 'Miami',
    state: 'FL',
    country: 'US',
    is_proven: true,
    health_tested: true,
    akc_registered: true,
    description: 'Titan is a rare Lilac Tan French Bulldog carrying fluffy. He is a proven sire with two litters on the ground. Strong topline, wide chest, and excellent temperament. Genetic panel available. Will travel to approved females.',
    photos: ['https://images.dog.ceo/breeds/retriever-golden/n02099601_109.jpg', 'https://images.dog.ceo/breeds/retriever-golden/n02099601_7780.jpg'],
    availability: 'limited',
    status: 'active',
    is_featured: true,
    owner_name: 'Carlos M.',
    owner_since: '2023',
  },
  {
    id: 'demo-4',
    name: 'Rex',
    breed: 'German Shepherd',
    color: 'Black & Tan',
    genetics: '',
    weight_lbs: 88,
    age_years: 4,
    stud_fee: 1500,
    contact_for_price: false,
    city: 'Dallas',
    state: 'TX',
    country: 'US',
    is_proven: true,
    health_tested: true,
    akc_registered: true,
    description: 'Rex is a working-line German Shepherd with SchH1 title. OFA hips and elbows certified Good. He has produced multiple litters with strong drives, correct structure, and stable temperament. Suitable for working and sport dog programs.',
    photos: ['https://images.dog.ceo/breeds/retriever-golden/n02099601_109.jpg', 'https://images.dog.ceo/breeds/retriever-golden/n02099601_7780.jpg'],
    availability: 'available',
    status: 'active',
    is_featured: false,
    owner_name: 'James T.',
    owner_since: '2020',
  },
  {
    id: 'demo-5',
    name: 'Brutus',
    breed: 'Rottweiler',
    color: 'Black & Mahogany',
    genetics: '',
    weight_lbs: 115,
    age_years: 3,
    stud_fee: 1200,
    contact_for_price: false,
    city: 'Phoenix',
    state: 'AZ',
    country: 'US',
    is_proven: true,
    health_tested: true,
    akc_registered: true,
    description: 'Brutus is a large-framed, heavy-boned Rottweiler with a broad, blocky head and deep rust markings. OFA hips Good, cardiac and eye clear. He has produced four litters with consistent size and markings. Exceptional producer.',
    photos: ['https://images.dog.ceo/breeds/labrador/n02099712_5679.jpg', 'https://images.dog.ceo/breeds/labrador/n02099712_6426.jpg'],
    availability: 'available',
    status: 'active',
    is_featured: false,
    owner_name: 'Tony V.',
    owner_since: '2021',
  },
  {
    id: 'demo-6',
    name: 'Cooper',
    breed: 'Golden Retriever',
    color: 'Light Golden',
    genetics: '',
    weight_lbs: 72,
    age_years: 3.5,
    stud_fee: 800,
    contact_for_price: false,
    city: 'Seattle',
    state: 'WA',
    country: 'US',
    is_proven: false,
    health_tested: true,
    akc_registered: true,
    description: 'Cooper is a light golden male from champion lines. OFA hips and elbows Excellent, cardiac and eye certifications current. PRA clear. Beautiful coat, excellent conformation, and calm temperament. First litters being planned now.',
    photos: ['https://images.dog.ceo/breeds/rottweiler/n02106550_4910.jpg', 'https://images.dog.ceo/breeds/rottweiler/n02106550_6310.jpg'],
    availability: 'available',
    status: 'active',
    is_featured: false,
    owner_name: 'Lisa H.',
    owner_since: '2023',
  },
  {
    id: 'demo-7',
    name: 'Gatsby',
    breed: 'Standard Poodle',
    color: 'Parti White & Brown',
    genetics: '',
    weight_lbs: 62,
    age_years: 4,
    stud_fee: 1800,
    contact_for_price: false,
    city: 'New York',
    state: 'NY',
    country: 'US',
    is_proven: true,
    health_tested: true,
    akc_registered: true,
    description: 'Gatsby is a parti Standard Poodle from multi-generation health-tested lines. OFA hips Good, CAER and SA clear. He has five proven litters producing parti and phantom puppies. Correct, balanced structure and excellent coat quality.',
    photos: ['https://images.dog.ceo/breeds/poodle-standard/n02113799_3356.jpg', 'https://images.dog.ceo/breeds/poodle-standard/n02113799_639.jpg'],
    availability: 'available',
    status: 'active',
    is_featured: false,
    owner_name: 'Amanda P.',
    owner_since: '2020',
  },
  {
    id: 'demo-8',
    name: 'Diesel',
    breed: 'Doberman',
    color: 'Blue',
    genetics: '',
    weight_lbs: 95,
    age_years: 3,
    stud_fee: 1400,
    contact_for_price: false,
    city: 'Chicago',
    state: 'IL',
    country: 'US',
    is_proven: true,
    health_tested: true,
    akc_registered: true,
    description: 'Diesel is a rare Blue Doberman with natural ears and tail. DCM and vWD clear. OFA hips and cardiac certified. He is a proven sire with two litters. Long, clean neck, correct angulation, and high drive. Excellent producer of type.',
    photos: ['https://images.dog.ceo/breeds/doberman/n02107142_12076.jpg', 'https://images.dog.ceo/breeds/doberman/n02107142_4663.jpg'],
    availability: 'available',
    status: 'active',
    is_featured: false,
    owner_name: 'David C.',
    owner_since: '2022',
  },
]
